<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Conclusion" data-toc-modified-id="Conclusion-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Conclusion</a></span></li><li><span><a href="#Goal" data-toc-modified-id="Goal-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Goal</a></span></li><li><span><a href="#Load" data-toc-modified-id="Load-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Load</a></span></li><li><span><a href="#Testing-each-subroutine" data-toc-modified-id="Testing-each-subroutine-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Testing each subroutine</a></span><ul class="toc-item"><li><span><a href="#get-rebalancers" data-toc-modified-id="get-rebalancers-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>get rebalancers</a></span></li><li><span><a href="#get-rebalancing-flows" data-toc-modified-id="get-rebalancing-flows-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>get rebalancing flows</a></span></li><li><span><a href="#compute" data-toc-modified-id="compute-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>compute</a></span></li></ul></li></ul></div>

# Conclusion

# Goal

Testing the initialization routines before introducing it for real into the code. 

# Load

In [5]:
%load_ext autoreload
%autoreload 2
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import pickle
import os
import pandas as pd

from amod_ed.result_analysis import plot_ri, print_final_flows, plot_cost_all_path, plot_ri_list, plot_balance_list
from amod_ed.result_analysis import plot_stop_and_cost

In [6]:
subfolder='unstucking_balance'

In [7]:
n_nodes=10

In [8]:
path='Data/'+str(n_nodes)+'Nodes/outputs/'+subfolder

In [9]:
print(os.listdir(path))

['new_init.pkl', 'ni_to_10000.pkl', 'initial_setup.pkl', 'ni_to_5000.pkl']


In [10]:
filename=os.listdir(path)[2]
print(filename)

with open(os.path.join(path, filename), 'rb') as f:
        G_FW, OD, ri_FW, n_outer, n_inner, balance, opt_res, OD_list, balance_list, params = pickle.load(f)

initial_setup.pkl


In [11]:
params

{'L': 10000,
 'ni': 1000,
 'no': 20,
 'ev': False,
 'sc': 'relative_progress',
 'fu': False,
 'ri_smoothing': False,
 'update_factor': False,
 'FW_tol': 0,
 'tol': 0}

# Testing each subroutine

## get rebalancers

ok

## get rebalancing flows

In [36]:
from amod_ed.result_analysis import print_final_flows

In [52]:
G_ref = G_FW[3][-1]

In [53]:
print_final_flows(G_FW[3])

('0', '1')  :  12.644357887559229
('0', '2')  :  7.279746201901883
('0', '3')  :  10.38865326290476
('0', '7')  :  6.623875126869138
('0', 'R')  :  13.911204437606552
('0', '0_p')  :  6.096378671228969
('1', '0')  :  12.584284102390578
('1', '4')  :  12.644357887559229
('2', '0')  :  7.262198878965337
('2', '6')  :  7.279746201901883
('3', '0')  :  10.446379967338036
('3', '9')  :  4.867168759384326
('3', '5_p')  :  5.521484503520423
('4', '1')  :  12.584284102390578
('4', '5')  :  16.68901370752173
('4', '8')  :  0.0
('4', '5_p')  :  6.2167174143222
('5', '4')  :  16.60537067722697
('5', 'R')  :  16.68901370752173
('5', '5_p')  :  13.394629322773039
('6', '2')  :  7.262198878965337
('6', '0_p')  :  7.279746201901883
('7', '0')  :  6.651352639376588
('7', '0_p')  :  6.623875126869138
('8', '4')  :  0.0
('9', '3')  :  4.888704110260986
('9', '5_p')  :  4.867168759384326


In [42]:
from amod_ed.initialization_rebalancers import _get_rebalancing_flows

In [55]:
f_r, edge_list = _get_rebalancing_flows(G_ref)

In [56]:
f_r

array([12.64435789,  0.        ,  0.        ,  0.        , 13.91120444,
        0.        ,  2.19563084, 12.64435789,  7.26219888,  0.        ,
       10.44637997,  0.        ,  0.        ,  2.19563084, 16.68901371,
        0.        ,  0.        ,  0.        , 16.68901371,  0.        ,
        7.26219888,  0.        ,  6.65135264,  0.        ,  0.        ,
        4.88870411,  0.        ])

In [57]:
nodes_list

['0', '0_p', '1', '2', '3', '4', '5', '5_p', '6', '7', '8', '9', 'R']

In [58]:
edge_list

[('0', '1'),
 ('0', '2'),
 ('0', '3'),
 ('0', '7'),
 ('0', 'R'),
 ('0', '0_p'),
 ('1', '0'),
 ('1', '4'),
 ('2', '0'),
 ('2', '6'),
 ('3', '0'),
 ('3', '9'),
 ('3', '5_p'),
 ('4', '1'),
 ('4', '5'),
 ('4', '8'),
 ('4', '5_p'),
 ('5', '4'),
 ('5', 'R'),
 ('5', '5_p'),
 ('6', '2'),
 ('6', '0_p'),
 ('7', '0'),
 ('7', '0_p'),
 ('8', '4'),
 ('9', '3'),
 ('9', '5_p')]

In [59]:
from amod_ed.initialization_rebalancers import _get_matrix

In [61]:
A = _get_matrix(G_ref, edge_list, nodes_list)

ok

## compute

In [66]:
from amod_ed.initialization_rebalancers import _compute_nearest_feasible

In [72]:
f_init_r = _compute_nearest_feasible(f_r, r_i, A, norm = 1)

Initialization problem status:  optimal


In [73]:
f_init_r

array([ 1.26433482e+01,  5.56767336e+00,  6.84037299e+00,  7.64904653e+00,
       -1.25043215e+01,  5.56766815e+00,  2.19664053e+00,  1.26433478e+01,
        3.87315613e+00,  5.56767398e+00,  4.78275300e+00,  6.89839279e-01,
       -5.18304846e-04,  2.19664092e+00,  9.88981346e+00,  1.40760857e-06,
        1.42718164e-03,  5.68482606e+00,  1.25043216e+01,  8.38733096e+00,
        3.87315552e+00, -5.56767919e+00,  9.97685298e-01,  9.80424356e-06,
       -1.40760857e-06,  4.18937577e+00, -8.38823987e+00])

In [74]:
f_r

array([12.64435789,  0.        ,  0.        ,  0.        , 13.91120444,
        0.        ,  2.19563084, 12.64435789,  7.26219888,  0.        ,
       10.44637997,  0.        ,  0.        ,  2.19563084, 16.68901371,
        0.        ,  0.        ,  0.        , 16.68901371,  0.        ,
        7.26219888,  0.        ,  6.65135264,  0.        ,  0.        ,
        4.88870411,  0.        ])